# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: My Enki Blog
subtitle: A blog about me
url:   http://enkiblog.com
author:
  name:    Don Alias        # For copyright notice and ATOM feeds
  email:   don@enkiblog.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://enkiblog.com
      - http://secondaryopenid.com

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com

# Uncomment this if you use feedburner or any other feed proxy
#feed_proxy_url: http://feeds.feedburner.com/my_blog_name

# Add your id if you want badge on the sidebar
stackoverflow:
  id: 325564

# Add your twitter handle if you want your tweets to be displayed on the sidebar
twitter:
  id: medwezys
